import psutil

# for i in range(20):
#     cpu_percent = psutil.cpu_percent(interval=1, percpu=False)
#     print(f"Overall CPU usage after {i+1} second(s): {cpu_percent}%")
#     cpu_percent_true = psutil.cpu_percent(interval=1, percpu=True)
#     print(f"Per-CPU usage after {i+1} second(s): {cpu_percent_true}%")

print("="*60)
u_count_physical = psutil.cpu_count(logical=False)
print(f"Physical CPU count   : {u_count_physical}")
print("="*60)
cpu_thread = psutil.cpu_count()
print(f"Logical CPU thread   : {cpu_thread}")
print("="*60)
cpu_usage = psutil.cpu_times()
print(f"Overall CPU usage    : {cpu_usage}%")

# for x in range(10):
#     print(psutil.cpu_percent(interval=1, percpu=True))
print("="*60)
memory_vir = psutil.virtual_memory()
print(f"Virtual Memory       : {memory_vir}%")
print("="*60)
swap_mem = psutil.swap_memory()
print(f"Swap Memory          : {swap_mem}%")
print("="*60)
disk_partation_info = psutil.disk_partitions()
print(f"Disk Partation Info  : {disk_partation_info}%")
print("="*60)
disk_usage = psutil.disk_usage('/')
print(f"Disk Usage           : {disk_usage}%")
print("="*60)
disk_io_counters = psutil.disk_io_counters()
print(f"Disk IO Counters     : {disk_io_counters}%")
print("="*60)
net_io_counters = psutil.net_io_counters()
print(f"Network IO Counters  : {net_io_counters}%")
print("="*60)

# psutil.pids()
# print(f"Process IDs          : {psutil.pids()}%")
p = psutil.Process(3149)
print(f"Process Name         : {p.name()}%")
print("="*60)
print(f"Process Status       : {p.status()}%")
print("="*60)
print(f"Process Creation Time: {p.create_time()}%")
print("="*60)
print(f"Process CPU Times    : {p.cpu_times()}%")
print("="*60)
print(f"Process Memory Info  : {p.memory_info()}%")
print("="*60)
print(f"Process Open Files   : {p.open_files()}%")
print("="*60)
print(f"Process Connections  : {p.connections()}%")
print("="*60)
print(f"Process Threads      : {p.threads()}%")
print("="*60)
print(f"Process Environment  : {p.environ()}%")
print("="*60)
